# Generated by Django 6.0.4 on 2026-04-20 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('lieu_depart', models.CharField(max_length=255)),
                ('lieu_destination', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee_agriculteur', 'Acceptée par agriculteur'), ('refusee_agriculteur', 'Refusée par agriculteur'), ('en_attente_transporteur', 'En attente transporteur'), ('acceptee_transporteur', 'Acceptée par transporteur'), ('refusee_transporteur', 'Refusée par transporteur'), ('en_route', 'En route'), ('livree', 'Livrée')], default='en_attente', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_acheteur', to=settings.AUTH_USER_MODEL)),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_agriculteur', to=settings.AUTH_USER_MODEL)),
                ('transporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_transporteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
