# Generated by Django 5.2.13 on 2026-04-22 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeTransporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande_id', models.IntegerField(unique=True)),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('lieu_depart', models.CharField(blank=True, max_length=255)),
                ('lieu_destination', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('en_attente_transporteur', 'En attente transporteur'), ('acceptee_transporteur', 'Acceptee par transporteur'), ('refusee_transporteur', 'Refusee par transporteur'), ('en_route', 'En route'), ('livree', 'Livree')], default='en_attente_transporteur', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acheteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraisons_acheteur', to=settings.AUTH_USER_MODEL)),
                ('agriculteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraisons_agriculteur', to=settings.AUTH_USER_MODEL)),
                ('transporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_transporteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
