# Generated by Django 5.2.13 on 2026-04-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraison', '0002_course_fields'),
        ('livraison', '0002_demandetransporteur_delete_commande'),
    ]

    operations = [
    ]
