from django.urls import path
from .views import (
    splash_view,
    home_view,
    services_view,
    contact_view,
    ensavoir_view,
    signup_view,
    login_view,
    api_login,
    logout_view,
    agriculteur_view,
    acheteur_view,
    transporteur_view,
    organisation_view,
    adminpage_view,
    approve_user,
    reject_user,
    session_info,
    api_farms,
    api_add_farm,
    api_profile,
    api_change_password,
    public_market_stats,
    admin_dynamic_stats,
)

urlpatterns = [
    path('', home_view, name='home'),
    path('splash/', splash_view, name='splash'),

    path('services/', services_view, name='services'),
    path('contact/', contact_view, name='contact'),
    path('ensavoir/', ensavoir_view, name='ensavoir'),

    path('signup/', signup_view, name='signup'),
    path('register/', signup_view, name='register'),
    path('login/', login_view, name='login'),
    path('api/login/', api_login, name='api_login'),
    path('api/session-info/', session_info, name='session_info'),
    path('api/profile/', api_profile, name='api_profile'),
    path('api/change-password/', api_change_password, name='api_change_password'),
    path('api/public-stats/', public_market_stats, name='public_market_stats'),
    path('api/admin/stats/', admin_dynamic_stats, name='admin_dynamic_stats'),
    path('api/agriculteur/farms/', api_farms, name='api_farms'),
    path('api/agriculteur/farms/add/', api_add_farm, name='api_add_farm'),
    path('logout/', logout_view, name='logout'),
    path('agriculteur/', agriculteur_view, name='agriculteur'),
    path('acheteur/', acheteur_view, name='acheteur'),
    path('transporteur/', transporteur_view, name='transporteur'),
    path('organisation/', organisation_view, name='organisation'),

    path('adminpage/', adminpage_view, name='adminpage'),
    path('adminpage/approve/<int:id>/', approve_user, name='approve_user'),
    path('adminpage/reject/<int:id>/', reject_user, name='reject_user'),
]