# Generated by Django 6.0.3 on 2026-04-16 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('Legume', 'Légume'), ('Fruit', 'Fruit'), ('Animal', 'Animal'), ('Cereale', 'Céréale')], max_length=50)),
                ('prix_min', models.FloatField()),
                ('prix_max', models.FloatField()),
                ('photo', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProduitAgriculteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('quantite', models.IntegerField()),
                ('statut', models.CharField(choices=[('Disponible', 'Disponible'), ('Stock faible', 'Stock faible'), ('Rupture', 'Rupture')], default='Disponible', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
    ]
