# Generated by Django 6.0.3 on 2026-04-17 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_produitagriculteur_agriculteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitagriculteur',
            name='agriculteur',
        ),
    ]
