# Generated by Django 6.0.4 on 2026-04-18 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_produitagriculteur_listing_fields'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitagriculteur',
            name='agriculteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_agriculteur', to='users.profile'),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('refusee', 'Refusée'), ('en_preparation', 'En préparation'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=30)),
                ('adresse_livraison', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('total', models.FloatField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_acheteur', to='users.profile')),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_agriculteur', to='users.profile')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.FloatField()),
                ('sous_total', models.FloatField(default=0)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='produits.commande')),
                ('produit_agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='produits.produitagriculteur')),
            ],
        ),
    ]
