# Generated by Django 5.2.13 on 2026-04-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(max_length=100),
        ),
    ]
