# Generated by Django 6.0.4 on 2026-05-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_alter_produit_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('refusee', 'Refusée'), ('en_preparation', 'En préparation'), ('en_attente_transporteur', 'En attente transporteur'), ('expediee', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=30),
        ),
    ]
