# Generated by Django 6.0.3 on 2026-04-14 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('agriculteur', 'Agriculteur'), ('acheteur', 'Acheteur'), ('transporteur', 'Transporteur'), ('autres', 'Autres')], max_length=20)),
                ('phone', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('birth_city', models.CharField(max_length=150)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('other_type', models.CharField(blank=True, choices=[('veterinaire', 'Vétérinaire'), ('organisation', 'Organisation')], max_length=30, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surface', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('main_products', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace', models.CharField(blank=True, max_length=100, null=True)),
                ('establishment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('commercial_register', models.FileField(blank=True, null=True, upload_to='commercial_registers/')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_info', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TransporterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=255)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_info', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='vehicle_documents/')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.transporterinfo')),
            ],
        ),
    ]
