# Generated by Django 6.0.3 on 2026-04-19 15:21

from decimal import Decimal, InvalidOperation
from django.db import migrations, models


def backfill_farm_fields(apps, schema_editor):
    Farm = apps.get_model('users', 'Farm')
    for farm in Farm.objects.all():
        meta = {}
        for part in (farm.main_products or '').split('|'):
            part = part.strip()
            if not part or ':' not in part:
                continue
            raw_key, raw_value = part.split(':', 1)
            meta[raw_key.strip().lower()] = raw_value.strip()

        updated = False
        for field_name in ('wilaya', 'lieu', 'commune', 'adresse', 'culture'):
            if not getattr(farm, field_name) and meta.get(field_name):
                setattr(farm, field_name, meta[field_name])
                updated = True

        coords = meta.get('coords')
        if coords and (farm.latitude is None or farm.longitude is None):
            parts = [v.strip() for v in coords.split(',')]
            if len(parts) == 2:
                try:
                    farm.latitude = Decimal(parts[0].replace(',', '.'))
                    farm.longitude = Decimal(parts[1].replace(',', '.'))
                    updated = True
                except (InvalidOperation, ValueError):
                    pass

        if updated:
            farm.save(update_fields=['wilaya', 'lieu', 'commune', 'adresse', 'culture', 'latitude', 'longitude'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='commune',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='culture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='lieu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='wilaya',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.RunPython(backfill_farm_fields, migrations.RunPython.noop),
    ]
