# Generated by Django 6.0.4 on 2026-05-01 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_farm_adresse_farm_commune_farm_culture_farm_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type_alerte', models.CharField(choices=[('stock_faible', 'Stock Animaux Faible'), ('epidemie', 'Risque Épidémie'), ('campagne', 'Campagne Nationale'), ('urgent', 'Urgent')], default='stock_faible', max_length=20)),
                ('wilayas_cibles', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('creee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_visite', models.CharField(choices=[('consultation', 'Consultation'), ('vaccination', 'Vaccination'), ('urgence', 'Urgence'), ('suivi', 'Suivi'), ('chirurgie', 'Chirurgie')], default='consultation', max_length=20)),
                ('date_rdv', models.DateField()),
                ('heure_rdv', models.TimeField()),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('wilaya', models.CharField(blank=True, choices=[('01', 'Adrar'), ('02', 'Chlef'), ('03', 'Laghouat'), ('04', 'Oum El Bouaghi'), ('05', 'Batna'), ('06', 'Béjaïa'), ('07', 'Biskra'), ('08', 'Béchar'), ('09', 'Blida'), ('10', 'Bouïra'), ('11', 'Tamanrasset'), ('12', 'Tébessa'), ('13', 'Tlemcen'), ('14', 'Tiaret'), ('15', 'Tizi Ouzou'), ('16', 'Alger'), ('17', 'Djelfa'), ('18', 'Jijel'), ('19', 'Sétif'), ('20', 'Saïda'), ('21', 'Skikda'), ('22', 'Sidi Bel Abbès'), ('23', 'Annaba'), ('24', 'Guelma'), ('25', 'Constantine'), ('26', 'Médéa'), ('27', 'Mostaganem'), ('28', "M'Sila"), ('29', 'Mascara'), ('30', 'Ouargla'), ('31', 'Oran'), ('32', 'El Bayadh'), ('33', 'Illizi'), ('34', 'Bordj Bou Arréridj'), ('35', 'Boumerdès'), ('36', 'El Tarf'), ('37', 'Tindouf'), ('38', 'Tissemsilt'), ('39', 'El Oued'), ('40', 'Khenchela'), ('41', 'Souk Ahras'), ('42', 'Tipaza'), ('43', 'Mila'), ('44', 'Aïn Defla'), ('45', 'Naâma'), ('46', 'Aïn Témouchent'), ('47', 'Ghardaïa'), ('48', 'Relizane'), ('49', "El M'Ghair"), ('50', 'El Meniaa'), ('51', 'Ouled Djellal'), ('52', 'Bordj Baji Mokhtar'), ('53', 'Béni Abbès'), ('54', 'Timimoun'), ('55', 'Touggourt'), ('56', 'Djanet'), ('57', 'In Salah'), ('58', 'In Guezzam')], max_length=2)),
                ('animaux_concernes', models.CharField(blank=True, max_length=255)),
                ('nombre_animaux', models.PositiveIntegerField(default=1)),
                ('description_probleme', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('refuse', 'Refusé'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('note_veterinaire', models.TextField(blank=True)),
                ('diagnostic', models.TextField(blank=True)),
                ('traitement', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_rdv', to='users.profile')),
            ],
            options={
                'ordering': ['-date_rdv', '-heure_rdv'],
            },
        ),
        migrations.CreateModel(
            name='MessageVet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus_vet', to='users.profile')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes_vet', to='users.profile')),
                ('rdv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='veterinaire.rendezvous')),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='VeterinaireProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(blank=True, max_length=200)),
                ('numero_ordre', models.CharField(blank=True, max_length=100)),
                ('wilaya_principale', models.CharField(blank=True, choices=[('01', 'Adrar'), ('02', 'Chlef'), ('03', 'Laghouat'), ('04', 'Oum El Bouaghi'), ('05', 'Batna'), ('06', 'Béjaïa'), ('07', 'Biskra'), ('08', 'Béchar'), ('09', 'Blida'), ('10', 'Bouïra'), ('11', 'Tamanrasset'), ('12', 'Tébessa'), ('13', 'Tlemcen'), ('14', 'Tiaret'), ('15', 'Tizi Ouzou'), ('16', 'Alger'), ('17', 'Djelfa'), ('18', 'Jijel'), ('19', 'Sétif'), ('20', 'Saïda'), ('21', 'Skikda'), ('22', 'Sidi Bel Abbès'), ('23', 'Annaba'), ('24', 'Guelma'), ('25', 'Constantine'), ('26', 'Médéa'), ('27', 'Mostaganem'), ('28', "M'Sila"), ('29', 'Mascara'), ('30', 'Ouargla'), ('31', 'Oran'), ('32', 'El Bayadh'), ('33', 'Illizi'), ('34', 'Bordj Bou Arréridj'), ('35', 'Boumerdès'), ('36', 'El Tarf'), ('37', 'Tindouf'), ('38', 'Tissemsilt'), ('39', 'El Oued'), ('40', 'Khenchela'), ('41', 'Souk Ahras'), ('42', 'Tipaza'), ('43', 'Mila'), ('44', 'Aïn Defla'), ('45', 'Naâma'), ('46', 'Aïn Témouchent'), ('47', 'Ghardaïa'), ('48', 'Relizane'), ('49', "El M'Ghair"), ('50', 'El Meniaa'), ('51', 'Ouled Djellal'), ('52', 'Bordj Baji Mokhtar'), ('53', 'Béni Abbès'), ('54', 'Timimoun'), ('55', 'Touggourt'), ('56', 'Djanet'), ('57', 'In Salah'), ('58', 'In Guezzam')], max_length=2)),
                ('bio', models.TextField(blank=True)),
                ('experience_annees', models.PositiveIntegerField(default=0)),
                ('tarif_consultation', models.DecimalField(decimal_places=2, default=2000, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_consultations', models.PositiveIntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vet_profile', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TourneeVeterinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('wilayas', models.JSONField(default=list)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('services_offerts', models.TextField(blank=True)),
                ('tarif_special', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('alerte_admin', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('veterinaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournees', to='veterinaire.veterinaireprofile')),
            ],
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='veterinaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='veterinaire.veterinaireprofile'),
        ),
        migrations.CreateModel(
            name='EvaluationVet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(default=5)),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_donnees', to='users.profile')),
                ('rdv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='veterinaire.rendezvous')),
                ('veterinaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_recues', to='veterinaire.veterinaireprofile')),
            ],
        ),
    ]
