# Generated by Django 6.0.4 on 2026-05-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaire', '0003_alerteadmin_destinataire_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinaireprofile',
            name='tarif_consultation',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
    ]
