# Generated by Django 6.0.4 on 2026-05-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourneeorganisateur',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Tournée Organisateur', 'verbose_name_plural': 'Tournées Organisateurs'},
        ),
        migrations.AlterField(
            model_name='tourneeorganisateur',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='tourneeorganisateur',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description / Ce qui sera fait'),
        ),
        migrations.AlterField(
            model_name='tourneeorganisateur',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom de la tournée'),
        ),
        migrations.AlterField(
            model_name='tourneeorganisateur',
            name='statut',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20),
        ),
        migrations.AlterField(
            model_name='tourneeorganisateur',
            name='wilaya',
            field=models.CharField(blank=True, choices=[('01', 'Adrar'), ('02', 'Chlef'), ('03', 'Laghouat'), ('04', 'Oum El Bouaghi'), ('05', 'Batna'), ('06', 'Béjaïa'), ('07', 'Biskra'), ('08', 'Béchar'), ('09', 'Blida'), ('10', 'Bouïra'), ('11', 'Tamanrasset'), ('12', 'Tébessa'), ('13', 'Tlemcen'), ('14', 'Tiaret'), ('15', 'Tizi Ouzou'), ('16', 'Alger'), ('17', 'Djelfa'), ('18', 'Jijel'), ('19', 'Sétif'), ('20', 'Saïda'), ('21', 'Skikda'), ('22', 'Sidi Bel Abbès'), ('23', 'Annaba'), ('24', 'Guelma'), ('25', 'Constantine'), ('26', 'Médéa'), ('27', 'Mostaganem'), ('28', "M'Sila"), ('29', 'Mascara'), ('30', 'Ouargla'), ('31', 'Oran'), ('32', 'El Bayadh'), ('33', 'Illizi'), ('34', 'Bordj Bou Arréridj'), ('35', 'Boumerdès'), ('36', 'El Tarf'), ('37', 'Tindouf'), ('38', 'Tissemsilt'), ('39', 'El Oued'), ('40', 'Khenchela'), ('41', 'Souk Ahras'), ('42', 'Tipaza'), ('43', 'Mila'), ('44', 'Aïn Defla'), ('45', 'Naâma'), ('46', 'Aïn Témouchent'), ('47', 'Ghardaïa'), ('48', 'Relizane'), ('49', "El M'Ghair"), ('50', 'El Meniaa'), ('51', 'Ouled Djellal'), ('52', 'Bordj Baji Mokhtar'), ('53', 'Béni Abbès'), ('54', 'Timimoun'), ('55', 'Touggourt'), ('56', 'Djanet'), ('57', 'In Salah'), ('58', 'In Guezzam')], max_length=2, verbose_name='Wilaya'),
        ),
    ]
